name: clipgan
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipywidgets
  - python>=3.9.1
  - pip
  - voila
  - einops
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==1.9.0+cu111
    - ftfy 
    - regex 
    - tqdm 
    - omegaconf 
    - pytorch-lightning
    - torchvision
    - tensorboard
